### PR TITLE
New implement for grace notes.

### PR DESCRIPTION
**Pull request by unbored**
No more extra scores. Utilizing lilypond's grace mechanism. Slurs on grace could be added easily in the future.
TODO: lilypond seems work abnormally when a single note with explicit beam adjustment is put in a grace. A silent note helps suppress the warning but yields another problem.

### CODE REVIEW

**Comment by unbored** [comment]
And let's discuss where the bracket should put in the grace. Usually a slur in a grace starts at the first note and stops at the main note, while in the case of after grace, starts at the main note and stops at the last note. Then maybe `g([12] 3 )` and `1 ( [23])g` would be enough. If there are others situations that the slurs might start at the middle, maybe `g[1(2] 3 )` and `1 ( [2)3]g` would be better?

**Comment by ssb22** [comment]
Thanks.  In Western music, Lilypond has [appoggiatura and acciaccatura commands](https://lilypond.org/doc/v2.25/Documentation/learning/grace-notes) that automatically add the slur, so you don't have to put the slur in separately.  That makes me wonder if we need new commands instead of a new slur syntax.  But do we have examples of published jianpu with extra slurs from grace notes?  I thought the curve we were already drawing *was* the slur (because I didn't see any other in the scores I looked at), but maybe I didn't see enough scores.

**Comment by unbored** [comment]
> Thanks. In Western music, Lilypond has [appoggiatura and acciaccatura commands](https://lilypond.org/doc/v2.25/Documentation/learning/grace-notes) that automatically add the slur, so you don't have to put the slur in separately. That makes me wonder if we need new commands instead of a new slur syntax. But do we have examples of published jianpu with extra slurs from grace notes? I thought the curve we were already drawing _was_ the slur (because I didn't see any other in the scores I looked at), but maybe I didn't see enough scores.

The curve is just a symbol indicating a grace, not the slur, at least in the scores I've ever seen. I know there is appoggiatura and acciaccatura, but the afterGrace command produces no slurs, and some scores I've met happen to have afterGrace with slurs, so comes the problem. I've never seen a grace with slurs starting at the middle, so maybe what I'm considering is meaningless.

**Comment by unbored** [comment]
I don't think the patch you made works. In my test case it breaks. Here is the test:
```
% jianpu-ly.py 文檔
title=Test
composer=test
arranger=测试
poet=test

2/4
Harm:
s1, g[,1,,d2] s2,,, bq3'' q,123 q4' [,,d3'''4]g
5 -
:Harm
g[3] 6 - s5. ( d6,, q7''' ) #q1 q#12,
R{
,,#3''4 ( s,5,6 s,,7,#1 ) q'''2,,3 '4'5 -
}
A{
5 - 6 - | 7 - - -
}

H:天地玄黄宇宙洪荒日月盈昃
```

When I say the distance I mean the distance between the whole grace and the main note, not the length of the beams after the grace note (of course it is also a problem, but not as ugly in my view). After the patch the curve sometimes goes too low, even lower than the main note. I would prefer the original code.

**Comment by unbored** [comment]
Do you have the same lilypond issue? A simple sample produces the warning and wrong output:
```
\relative c'{
  \grace{c16[]} c4 \grace{c16[]} c4
}
```
I'm using 2.24.3 on MacOS. Maybe we should firstly figure out why lilypond goes wrong.

**Pull request merged**
